# Generated by Django 2.0.3 on 2018-04-09 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('director', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=250)),
                ('nivel_formacion', models.CharField(choices=[(' pregrado ', ' Pregrado '), (' especializacion ', ' Especializacion '), (' maestria ', ' Maestria '), (' doctorado ', ' Doctorado ')], default='No seleccion', max_length=50)),
                ('titulo', models.CharField(max_length=250)),
                ('tipo_vinculacion', models.CharField(choices=[(' catedra', 'Catedra'), (' tiempo_completo', 'Tiempo completo'), (' ocacional', ' Ocacional')], default='No seleccion', max_length=50)),
                ('representante_facultad_investigacion', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('decano', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('estatus', models.CharField(max_length=50)),
                ('horas_recomendadas', models.CharField(max_length=50)),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.Docente')),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('horas_recomendadas', models.CharField(max_length=50)),
                ('tipo_proyecto', models.CharField(choices=[('proyecto_investigacion', 'Proyecto de investigacion'), ('proyecto_investigacion_institucional', 'Proyecto de investigacion institucional'), ('proyecto_investigacion_interno', 'Proyecto de investigacion interno')], default='No seleccion', max_length=150)),
                ('joven_investigador', models.CharField(max_length=150, null=True)),
                ('coinvestigador', models.ManyToManyField(related_name='_proyectoinvestigacion_coinvestigador_+', to='sistemaDocentes.Docente')),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistemaDocentes.Docente')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistemaDocentes.GrupoInvestigacion')),
                ('tutor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sistemaDocentes.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='SemilleroInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('horas_recomendadas', models.CharField(max_length=50)),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.Docente')),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.Facultad')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.Facultad'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='falcultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.Facultad'),
        ),
    ]
