# Generated by Django 2.0.3 on 2018-04-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDocentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('movilidad_internacional', 'Movilidad internacional'), ('movilidad_nacional', ' Movilidad nacional '), ('diplomado ', 'Diplomado')], default='No seleccion', max_length=50)),
                ('descripcion', models.CharField(max_length=350)),
                ('plazo_entrega', models.IntegerField(max_length=50)),
                ('tiempo', models.CharField(choices=[('año(s)', 'Año(s)'), ('mes(s)', 'Mes(s)'), ('dia(s)', 'Dia(s)')], default='No seleccion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Compromiso_Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(max_length=250)),
                ('beneficios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.Beneficios')),
                ('docente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='TipologiaProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.ClasificacionProductos')),
            ],
        ),
        migrations.AddField(
            model_name='compromiso_docente',
            name='tipologia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDocentes.TipologiaProductos'),
        ),
    ]
