# Generated by Django 2.0.3 on 2018-04-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDocentes', '0003_auto_20180416_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineas_investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo_Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350)),
            ],
        ),
        migrations.AlterField(
            model_name='docente',
            name='nivel_formacion',
            field=models.CharField(choices=[(' pregrado ', ' Pregrado '), (' especializacion ', ' Especializacion '), (' maestria ', ' Maestria '), (' doctorado ', ' Doctorado '), ('phd', 'PhD')], default='No seleccion', max_length=50),
        ),
        migrations.RemoveField(
            model_name='docente',
            name='titulo',
        ),
        migrations.AddField(
            model_name='grupoinvestigacion',
            name='lineas_investigacion',
            field=models.ManyToManyField(to='sistemaDocentes.Lineas_investigacion'),
        ),
        migrations.AddField(
            model_name='semilleroinvestigacion',
            name='lineas_investigacion',
            field=models.ManyToManyField(to='sistemaDocentes.Lineas_investigacion'),
        ),
        migrations.AddField(
            model_name='docente',
            name='titulo',
            field=models.ManyToManyField(to='sistemaDocentes.Titulo_Docente'),
        ),
    ]
