# Generated by Django 2.0.3 on 2018-04-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDocentes', '0004_auto_20180417_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='nivel_formacion',
        ),
        migrations.AddField(
            model_name='titulo_docente',
            name='nivel_formacion',
            field=models.CharField(choices=[(' pregrado ', ' Pregrado '), (' especializacion ', ' Especializacion '), (' maestria ', ' Maestria '), (' doctorado ', ' Doctorado '), ('phd', 'PhD')], default='No seleccion', max_length=50),
        ),
    ]
