# Generated by Django 2.0.3 on 2018-04-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDocentes', '0005_auto_20180417_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='representante_facultad_investigacion',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=2),
        ),
    ]
