# Generated by Django 2.0.3 on 2018-04-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDocentes', '0006_auto_20180417_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='tipo_vinculacion',
            field=models.CharField(choices=[(' catedra', 'Catedra'), (' planta', 'Planta'), (' ocacional', ' Ocacional')], default='No seleccion', max_length=50),
        ),
    ]
