# Generated by Django 2.0.3 on 2018-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDocentes', '0007_auto_20180418_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='tipo_vinculacion',
            field=models.CharField(choices=[(' Catedra', 'Catedra'), (' Planta', 'Planta'), (' Ocacional', ' Ocacional')], default='No seleccion', max_length=50),
        ),
    ]
