# Generated by Django 2.0.3 on 2018-05-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDocentes', '0008_auto_20180521_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='codigo',
        ),
    ]
